name: CI/CD Workflow

on:
  push:
    branches:
      - hitesh
      - rohit
      - staging
      - main
  pull_request:
    branches:
      - staging
      - main

jobs:
  merge-to-staging:
    if: github.ref == 'refs/heads/hitesh' || github.ref == 'refs/heads/rohit'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Merge into staging
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch origin
          git checkout staging
          git merge --no-ff $GITHUB_REF -m "Auto-merge $GITHUB_REF into staging"
          git push origin staging

  deploy-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ywsckglw/web/bigcloudy.com/public_html
            /bin/bash /home/ywsckglw/project-management/deploy.sh
