name: CI/CD Deploy

on:
  push:
    branches:
      - staging     # auto deploy to staging
  workflow_dispatch:   # allow manual trigger for production

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.cloudcarehost.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Use the ssh-agent action for reliable key handling
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add known host
        run: |
          # The agent handles the key, so we only need to add the known_host
          ssh-keyscan -p 19422 -H "${{ secrets.DEPLOY_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to Staging
        run: |
          ssh -p 19422 ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
            "/home/cloudcarehost/ci-cd/deploy.sh staging"

  deploy-production:
    if: github.event_name == 'workflow_dispatch'   # manual only
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://cloudcarehost.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Use the ssh-agent action for reliable key handling
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add known host
        run: |
          # The agent handles the key, so we only need to add the known_host
          ssh-keyscan -p 19422 -H "${{ secrets.DEPLOY_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to Production
        run: |
          ssh -p 19422 ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
            "/home/cloudcarehost/ci-cd/deploy.sh production"
