name: CI/CD Deploy

on:
  push:
    branches:
      - staging     # auto deploy to staging
  workflow_dispatch:   # allow manual trigger for production

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.cloudcarehost.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Staging with password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: 22
          script: /home/cloudcarehost/ci-cd/deploy.sh staging

  deploy-production:
    if: github.event_name == 'workflow_dispatch'   # manual only
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://cloudcarehost.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production with password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: 19422
          script: /home/cloudcarehost/ci-cd/deploy.sh production
